== Mr. Taskman

Mr-Taskman aims at rendering other *third-party* project management tools like **Trello** unnecessary.
You have a **#board** channel, where all tasks are displayed.
It will includes most basic functionallity like: *creating*, *editing*, *adding people*, *removing people*, *adding a deadline* and the like.

image:https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=for-the-badge[PRs Welcome, link=http://makeapullrequest.com]
image:https://img.shields.io/github/contributors/rbrtbrnschn/mr-taskman?style=for-the-badge[Contributors]
image:https://img.shields.io/github/v/release/rbrtbrnschn/mr-taskman?style=for-the-badge[release, link=https://GitHub.com/rbrtbrnschn/mr-taskman/releases/]
image:https://img.shields.io/github/commits-since/rbrtbrnschn/mr-taskman/v0.0.1.svg?style=for-the-badge[commits, link=https://GitHub.com/rbrtbrnschn/mr-taskman/commit/]
image:https://img.shields.io/github/issues/rbrtbrnschn/mr-taskman.svg?style=for-the-badge[issues open, link=https://GitHub.com/Naereen/StrapDown.js/issues/]
image:https://img.shields.io/github/issues-closed/rbrtbrnschn/mr-taskman?style=for-the-badge[issues closed, link=https://GitHub.com/Naereen/StrapDown.js/issues?q=is%3Aissue+is%3Aclosed]
image:https://img.shields.io/discord/781046343476576258.svg?label=&logo=discord&logoColor=ffffff&color=7389D8&labelColor=6A7EC2[Discord, link=https://discord.gg/qhHjuqgJ6Y]
image:https://img.shields.io/github/license/rbrtbrnschn/mr-taskman?style=for-the-badge[liscense, link=https://github.com/rbrtbrnshcn/mr-taskman/blob/slave/LICENSE]

=== Open Source Project

*Feel free* to to make **pull request** *for everything you see fit*. You can always look which issues are open and work on that. If you have **any ideas**, feel free to open a new issue, and/or code it yourself and send the **pull request**.

It's simple. If you feel, the bot needs more awesome error messages, feel free to add some.

=== Installation

```bash
git clone https://github.com/rbrtbrnschn/mr-taskman
cd mr-taskman
npm install
mv .env.sample .env
```
Don't forget to also propegate your .env file with everything it needs.footnote:env[Tokens can be aquired on creating your own application & bot at https://discord.com/developers[discord.com/developers]]

=== Usage

```bash
npm run start:dev
```
All other available scripts can be found at [](#scripts)

=== Contributing

**Pull requests are very welcome**. For *major changes*, please open an issue first to discuss what you would like to change.

Please make sure to update tests as appropriate.

1. **Fork** the project
2. **Create a new branch** for the new-feature
3. **Push** your new added and commited changes to the new-branch branch.
4. **Send pull request**.


=== .env structure

|===
| KEY | VALUE
| NODE_ENV | development \|\| production
| DISCORD_CLIENT_ID | footnote:env[]
| DISCORD_CLIENT_SECRET | footnote:env[]
| DISCORD_BOT_TOKEN | footnote:env[]
| PATH2COMMANDS_DEV | <absolute path to thisProject/src/commands>
| PATH2COMMANDS_PROD | <absolute path to thisProject/src/commands>
| MONGODB_USER | <database user, defaults to read-only access if none is provided>
| MONGODB_PASS | <database user, defaults to read-only access if none is provided>
|===

=== Scripts
```json
{
  "build": "transpiles typescript and outputs to ./build",
  "start:dev": "runs ts-node via nodemon on ./src",
  "start": "serves ./build files",
  "lint": "runs eslint and watches .ts files",
  "lint:fix": "fixes all fixable linter problems"
}
```

=== FAQ

- *Q*: Why do I need my own discord application and bot? +
*A*: Solely for developer purposes, once you send the pull request and it gets merged, it will be using the .env at my production server. 
- *Q*: Do you accept all pull request? +
*A*: If you think your added feature is useful, we are most likely to merge it, yes.
- *Q*: I run into problems on installing, what went wrong? +
*A*: Feel free to checkout our https://discord.gg/qhHjuqgJ6Y[*Javascript Discord*], if you need any help.
- *Q*: Can I give input on what frameworks are being used? +
*A*: Sure, we appreciate any valuable input, be that framework suggestions, help with datastructures and the like.

=== License
https://choosealicense.com/licenses/mit/[MIT]

