== Mr. Taskman

Discord bot aiming at superseeding project management functionality of high end project managers like *Trello*.

image:https://img.shields.io/github/license/rbrtbrnschn/mr-taskman[liscense, link=https://github.com/rbrtbrnshcn/mr-taskman/blob/slave/LICENSE]
image:https://img.shields.io/github/v/release/rbrtbrnschn/mr-taskman[release, link=https://GitHub.com/rbrtbrnschn/mr-taskman/releases/]
image:https://img.shields.io/github/commits-since/rbrtbrnschn/mr-taskman/v0.0.1.svg[commits, link=https://GitHub.com/rbrtbrnschn/mr-taskman/commit/]
image:https://img.shields.io/github/issues/rbrtbrnschn/mr-taskman.svg[issues open, link=https://GitHub.com/Naereen/StrapDown.js/issues/]
image:https://img.shields.io/github/issues-closed/rbrtbrnschn/mr-taskman[issues closed, link=https://GitHub.com/Naereen/StrapDown.js/issues?q=is%3Aissue+is%3Aclosed]
image:https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square[PRs Welcome, link=http://makeapullrequest.com]
image:https://img.shields.io/discord/781046343476576258.svg?label=&logo=discord&logoColor=ffffff&color=7389D8&labelColor=6A7EC2[Discord, link=https://discord.gg/qhHjuqgJ6Y]

=== Open Source Project

*Feel free* to to make pull request *for everything you see fit*. You can always look which issues are open and work on that. If you have any ideas, feel free to open a new issue, and/or code it yourself and send the pull request.

It's simple. If you feel, the bot needs more awesome error messages, feel free to

1. fork the project and clone it to your harddrive
2. open and edit (ie. src/config.ts and add more error messages)
3. add, commit and push
4. send a pull request

And voila, your code may just be implemented into the production build.

=== Install

1. fork the project
2. clone the project
3. open terminal and navigate to the cloned project
4. npm install
5. rename .env.sample to `.env`
6. propegate .env file with your tokens, secrets and keys.footnote:env[Tokens can be aquired on creating your own application & bot at https://discord.com/developers[discord.com/developers]]

=== .env structure
DISCORD_CLIENT_ID=>footnote:env[]

DISCORD_CLIENT_SECRET=>footnote:env[]

DISCORD_BOT_TOKEN=>footnote:env[]

PATH2COMMANDS=<absolute path to thisProject/src/commands>

=== FAQ

- *Q*: Why do I need my own discord application and bot? +
*A*: Solely for developer purposes, once you send the pull request and it gets merged, it will be using the .env at my production server. 
- *Q*: Do you accept all pull request? +
*A*: If you think your added feature is useful, we are most likely to merge it, yes.
- *Q*: I run into problems on installing, what went wrong? +
*A*: Feel free to checkout our https://discord.gg/qhHjuqgJ6Y[*Javascript Discord*], if you need any help.
- *Q*: Can I give input on what frameworks are being used? +
*A*: Sure, we appreciate any valuable input, be that framework suggestions, help with datastructures and the like.

